dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
before_install:
  - npm i -g jshint
cache:
  yarn: true
script:
  - set -e
  - jshint --show-non-errors test/*.js || echo "Errors in jshint ignored bc it doesn't support async/await"
  - GEN_TESTS_QTY=20 yarn test
  - yarn run coveralls
