dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "6"
before_install:
  - npm i -g jshint
script:
  - set -e
  - npm run testrpc&
  - jshint --show-non-errors test/*.js
  - npm test
